on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ../roman-numbers

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        java-package: jdk
        cache: maven
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Static
      run: mvn verify
        
    - name: Jacoco
      run: mvn test jacoco:report
        
    - name: Coveralls Coverage Report Setup
      run: sed -i.bak 's/yourcoverallsprojectrepositorytoken/${{ secrets.COVERALLS_REPO_TOKEN }}/g' pom.xml
    
    - name: Coveralls Coverage Report Submission
      run: mvn coveralls:report
    
    - name: Cleanup Repository Token
      if: ${{ always() }}
      run: if [ -f "pom.xml.bak" ]; then mv pom.xml.bak pom.xml; fi
      

