on:
  push:
    branches:  
      - main 
      - dev
      - feature
  pull_request:
    branches:
      - main 
      - dev
      - feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        java-package: jdk
        cache: maven
        
    - name: Jacoco
      run: mvn -B clean package jacoco:report
      
    - name: jacoco-badge-generator
      uses: cicirello/jacoco-badge-generator@v2.8.1
                
    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage}}"
        echo "branches = ${{ steps.jacoco.outputs.branches}}"

    - name: Add badges
      run: git add .github
      
    - name: Coveralls GitHub Action
    uses: coverallsapp/github-action@v1


    - name: Coveralls
      run: mvn -B coveralls:report --define repoToken=${{ secrets.COVERALLS_REPO_TOKEN }}
    
